name: 'Save Docker Volumes to Cache'
description: 'Save Docker Volumes to GitHub Actions Cache to improve workflow execution time'
author: 'BYK'
inputs:
  volumes:
    description: 'A list of docker volumes to restore'
    required: true
  key:
    description: 'An explicit key for saving the cache'
    required: true
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes'
    required: false
branding:
  icon: 'archive'
  color: 'gray-dark'
runs:
  using: "composite"
  steps:
    - name: Prepare Docker Volume Caching
      id: prepare_cache
      shell: bash
      env:
        INPUTS_VOLUMES: ${{ inputs.volumes }}
      run: |
        PATHS=""
        while IFS= read -r volume ; do
          if [ -n "$volume" ]; then
            printf -v PATHS "$PATHS\n/var/lib/docker/volumes/$volume"
          fi
        done <<< "$INPUTS_VOLUMES"
        {
          echo 'paths<<EOF'
          echo "$PATHS"
          echo EOF
        } >> "$GITHUB_OUTPUT"

        # We need to use `--numeric-owner` with `tar` to avoid permission and ownership
        # issues when restoring docker volumes, so hack it (as actions/cache doesn't do this yet)
        sudo mv -n /usr/bin/tar /usr/bin/tar.orig
        echo '#!/bin/bash' | sudo tee /usr/bin/tar > /dev/null
        echo 'exec sudo /usr/bin/tar.orig --numeric-owner -p --same-owner "$@"' | sudo tee -a /usr/bin/tar > /dev/null
        sudo chmod +x /usr/bin/tar
        sudo chmod u+sx /usr/bin/tar

    - name: Save Docker Volumes to Cache
      uses: actions/cache/save@v4
      with:
        key: ${{ inputs.key }}
        path: ${{ steps.prepare_cache.outputs.paths }}
        upload-chunk-size: ${{ inputs.upload-chunk-size }}

    - name: Restore tar
      shell: bash
      run: |
        sudo mv -f /usr/bin/tar.orig /usr/bin/tar
